# Generated by Django 4.1 on 2023-01-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
