# Generated by Django 4.1 on 2023-01-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('company', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
