# Generated by Django 4.1 on 2023-01-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_det',
        ),
    ]
