# Generated by Django 4.1 on 2023-01-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_contact_contact_det'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video1',
            name='video',
        ),
        migrations.AddField(
            model_name='video1',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
